---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-thin

inputs:
  - name: routing-release-ci
  - name: cf-environment
outputs:

params:
  TOOLSMITHS_API_TOKEN:

run:
  path: routing-release-ci/ci/tasks/unclaim-cf-deployment-environment/task
