
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-thin

inputs:
- name: release
- name: routing-release-ci

outputs:
- name: vars-files

params:

run:
  path: routing-release-ci/ci/tasks/write-repo-sha-var-file/task
