---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-deploy

inputs:
  - name: networking-oss-deployments
  - name: zero-downtime-release
  - name: routing-release-ci
  - name: toolsmiths-metadata-dir

run:
  path: routing-release-ci/ci/tasks/deploy-zero-downtime-backends/task

params:
  ENVIRONMENT:
