---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-thin

inputs:
  - name: cf-deployment
  - name: routing-release-ci
  - name: source1
    optional: true
  - name: source2
    optional: true

outputs:
  - name: merged-operations

params:
  SOURCE1_DIR: ~
  SOURCE2_DIR: ~

run:
  path: routing-release-ci/ci/tasks/merge-ops-files/task
