---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-build

inputs:
  - name: env-name
  - name: routing-release-ci

outputs:
  - name: smoke-tests-ops-file

run:
  path: routing-release-ci/ci/tasks/update-smoke-tests-ops-file-for-toolsmiths/task
