
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/tas-runtime-thin

inputs:

outputs:
- name: gcp-key

params:
  GCP_SERVICE_ACCOUNT_KEY:

run:
  path: routing-release-ci/ci/tasks/write-gcp-service-account-key-file/task
