---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-deploy

inputs:
  - name: networking-oss-deployments
  - name: routing-release-ci
  - name: toolsmiths-metadata-dir
    optional: true

run:
  path: routing-release-ci/ci/tasks/create-zd-app/task

params:
  CF_APP_DOMAIN:
  CF_APP_NAME:
  CF_ORG:
  CF_SPACE:
  ENVIRONMENT:
  TCP: # set to 'true' if TCP route is desired
