---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-thin

inputs:
  - name: routing-release-ci
outputs:
  - name: cf-environment

params:
  ENVIRONMENT_TYPE: cf-deployment
  TOOLSMITHS_API_TOKEN:
  ENVIRONMENT_NOTES:
  ENVIRONMENT_NAME:
run:
  path: routing-release-ci/ci/tasks/claim-cf-deployment-environment/task
