---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/tas-runtime-thin

inputs:
  - name: routing-release-ci
  - name: cf-deployment-concourse-tasks
  - name: bbl-state
  - name: local-release

params:
  BBL_STATE_DIR:

run:
  path: routing-release-ci/ci/tasks/upload-local-release/task
