---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-thin

inputs:
  - name: version
  - name: cf-routing-bosh-release
  - name: routing-release-ci

outputs:
  - name: release-checksum

run:
  path: routing-release-ci/ci/tasks/create-release-checksum/task
