---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-thin

inputs:
  - name: networking-oss-deployments
  - name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/create-isolation-segment/task

params:
  CF_API:
  CF_ADMIN_USER: admin
  CF_SKIP_SSL_VALIDATION:
  ENVIRONMENT:
  ISO_SEG_NAME:
