---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-build

inputs:
- name: routing-release
- name: integration-config
- name: routing-release-ci
run:
  path: routing-release-ci/ci/tasks/run-rats/task

params:
  NODES: 12
  CONFIG_FILE_PATH: rats_integration_config.json
  GINKGO_ARGS:
