---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-deploy

inputs:
  - name: networking-oss-deployments
  - name: routing-release-ci
  - name: toolsmiths-metadata-dir
    optional: true

run:
  path: routing-release-ci/ci/tasks/setup-cf-env/task

params:
  CF_ADMIN_PASSWORD:
  CF_ADMIN_USER: admin
  CF_ORG:
  CF_PASSWORD:
  CF_SKIP_SSL_VALIDATION: true
  CF_SPACE:
  CF_SPACE_ROLE: SpaceDeveloper
  CF_USERNAME:
  ENVIRONMENT:
  SYSTEM_DOMAIN:
