---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-build

inputs:
  - name: routing-release-ci
  - name: routing-release
  - name: toolsmiths-metadata-dir
    optional: true

run:
  path: routing-release-ci/ci/tasks/check-zero-downtime-test-results/task

params:
  CF_APP_DOMAIN:
  CF_APP_NAME:
  THRESHOLD:
