---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/tas-runtime-thin

inputs:
  - name: routing-release
  - name: version
  - name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/check-release/task

params:
