---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-deploy

inputs:
  - name: networking-oss-deployments
  - name: toolsmiths-metadata-dir
    optional: true
  - name: gcp-stemcell
  - name: release-tarball
  - name: cipher-manifest
  - name: routing-release-ci

run:
  path: routing-release-ci/ci/tasks/run-cipher-suite/task

params:
  ENVIRONMENT:
  BOSH_DEPLOYMENT:
  MANIFEST:
  RELEASES_DIR:
  STEMCELL_REGEX:
