---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/tas-runtime-thin

inputs:
  - name: routing-api-cli-src
  - name: routing-release-develop
  - name: version
  - name: routing-release-ci

outputs:
  - name: cli-output

run:
  path: routing-release-ci/ci/tasks/create-final-routing-api-cli-release/task

params:
  CF_ROUTING_RELEASE_DIR: routing-release-develop
  OUTPUT_DIR: cli-output
